# coding: utf-8
"""zmq constants"""

# from ._cffi import C, c_constant_names
c_constant_names = [] # for now
from zmq.utils.constant_names import all_names, removed_in, new_in

g = globals()
for cname in c_constant_names:
    if cname.startswith("ZMQ_"):
        name = cname[4:]
    else:
        name = cname
    g[name] = getattr(C, cname)


from _version import zmq_version_info
version = zmq_version_info()
VERSION_MAJOR = version[0]
VERSION_MINOR = version[1]
VERSION_PATCH = version[2]

VERSION = "%d%02d%02d" % (VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)

# from zmq.h version 4.1.0
HAUSNUMERO = 156384712
ENOTSUP = HAUSNUMERO + 1
EPROTONOSUPPORT = HAUSNUMERO + 2
ENOBUFS = HAUSNUMERO + 3
ENETDOWN = HAUSNUMERO + 4
EADDRINUSE = HAUSNUMERO + 5
EADDRNOTAVAIL = HAUSNUMERO + 6
ECONNREFUSED = HAUSNUMERO + 7
EINPROGRESS = HAUSNUMERO + 8
ENOTSOCK = HAUSNUMERO + 9
EMSGSIZE = HAUSNUMERO + 10
EAFNOSUPPORT = HAUSNUMERO + 11
ENETUNREACH = HAUSNUMERO + 12
ECONNABORTED = HAUSNUMERO + 13
ECONNRESET = HAUSNUMERO + 14
ENOTCONN = HAUSNUMERO + 15
ETIMEDOUT = HAUSNUMERO + 16
EHOSTUNREACH = HAUSNUMERO + 17
ENETRESET = HAUSNUMERO + 18
EFSM = HAUSNUMERO + 51
ENOCOMPATPROTO = HAUSNUMERO + 52
ETERM = HAUSNUMERO + 53
EMTHREAD = HAUSNUMERO + 54
IO_THREADS = 1
MAX_SOCKETS = 2
IO_THREADS_DFLT = 1
MAX_SOCKETS_DFLT = 1024
PAIR = 0
PUB = 1
SUB = 2
REQ = 3
REP = 4
DEALER = 5
ROUTER = 6
PULL = 7
PUSH = 8
XPUB = 9
XSUB = 10
STREAM = 11
XREQ = DEALER
XREP = ROUTER
AFFINITY = 4
IDENTITY = 5
SUBSCRIBE = 6
UNSUBSCRIBE = 7
RATE = 8
RECOVERY_IVL = 9
SNDBUF = 11
RCVBUF = 12
RCVMORE = 13
FD = 14
EVENTS = 15
TYPE = 16
LINGER = 17
RECONNECT_IVL = 18
BACKLOG = 19
RECONNECT_IVL_MAX = 21
MAXMSGSIZE = 22
SNDHWM = 23
RCVHWM = 24
MULTICAST_HOPS = 25
RCVTIMEO = 27
SNDTIMEO = 28
LAST_ENDPOINT = 32
ROUTER_MANDATORY = 33
TCP_KEEPALIVE = 34
TCP_KEEPALIVE_CNT = 35
TCP_KEEPALIVE_IDLE = 36
TCP_KEEPALIVE_INTVL = 37
TCP_ACCEPT_FILTER = 38
IMMEDIATE = 39
XPUB_VERBOSE = 40
ROUTER_RAW = 41
IPV6 = 42
MECHANISM = 43
PLAIN_SERVER = 44
PLAIN_USERNAME = 45
PLAIN_PASSWORD = 46
CURVE_SERVER = 47
CURVE_PUBLICKEY = 48
CURVE_SECRETKEY = 49
CURVE_SERVERKEY = 50
PROBE_ROUTER = 51
REQ_CORRELATE = 52
REQ_RELAXED = 53
CONFLATE = 54
ZAP_DOMAIN = 55
ROUTER_HANDOVER = 56
MORE = 1
DONTWAIT = 1
SNDMORE = 2
NULL = 0
PLAIN = 1
CURVE = 2
IPV4ONLY = 31
DELAY_ATTACH_ON_CONNECT = IMMEDIATE
NOBLOCK                 = DONTWAIT
FAIL_UNROUTABLE         = ROUTER_MANDATORY
ROUTER_BEHAVIOR         = ROUTER_MANDATORY
EVENT_CONNECTED = 1
EVENT_CONNECT_DELAYED = 2
EVENT_CONNECT_RETRIED = 4
EVENT_LISTENING = 8
EVENT_BIND_FAILED = 16
EVENT_ACCEPTED = 32
EVENT_ACCEPT_FAILED = 64
EVENT_CLOSED = 128
EVENT_CLOSE_FAILED = 256
EVENT_DISCONNECTED = 512
EVENT_MONITOR_STOPPED = 1024
EVENT_ALL = ( EVENT_CONNECTED | EVENT_CONNECT_DELAYED | \
                EVENT_CONNECT_RETRIED | EVENT_LISTENING | \
                EVENT_BIND_FAILED | EVENT_ACCEPTED | \
                EVENT_ACCEPT_FAILED | EVENT_CLOSED | \
                EVENT_CLOSE_FAILED | EVENT_DISCONNECTED | \
                EVENT_MONITOR_STOPPED)

POLLIN = 1
POLLOUT = 2
POLLERR = 4
POLLITEMS_DFLT = 16
STREAMER = 1
FORWARDER = 2
QUEUE = 3


# errnos from Platform.net.cs
EPERM = 1
ENOENT = 2
ESRCH = 3
EINTR = 4
EIO = 5
ENXIO = 6
E2BIG = 7
ENOEXEC = 8
EBADF = 9
ECHILD = 10
EAGAIN = 11
ENOMEM = 12
EACCES = 13
EFAULT = 14
EBUSY = 16
EEXIST = 17
EXDEV = 18
ENODEV = 19
ENOTDIR = 20
EISDIR = 21
EINVAL = 22
ENFILE = 23
EMFILE = 24
ENOTTY = 25
EFBIG = 27
ENOSPC = 28
ESPIPE = 29
EROFS = 30
EMLINK = 31
EPIPE = 32
EDOM = 33
EDEADLK = 36
ENAMETOOLONG = 38
ENOLCK = 39
ENOSYS = 40
ENOTEMPTY = 41
EADDRINUSE = 100
EADDRNOTAVAIL = 101
ECONNREFUSED = 107
EINPROGRESS = 112
ENETDOWN = 116
ENOBUFS = 119
ENOTSOCK = 128
ENOTSUP = 129
EPROTONOSUPPORT = 135

# since it is 2.x, I don't have the spec with the values 
HWM = -1
MCAST_LOOP = -1
RECOVERY_IVL_MSEC = -1
UPSTREAM = -1
SWAP = -1
DOWNSTREAM = -1

removed = removed_in[(3,2,2)]
if version<(4,0,0):
    added = new_in[(4,0,0)]
    for n in globals().keys():
        if n in added:
            #del g[n]
            g[n]=-1
else:
    added = set()

__all__ = [name for name in all_names if name not in removed and name not in added]
# ugly hack to make test_undefined_constants pass
__all__.extend(["HWM", "MCAST_LOOP", "RECOVERY_IVL_MSEC", "UPSTREAM", "SWAP", "DOWNSTREAM"])


